# Generated by Django 4.2.6 on 2023-10-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_verified',
            new_name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='remaining_minutes_plan',
        ),
    ]
